#App
server.port=8080
server.forward-headers-strategy=framework
#DATABASE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/chillandchill?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}

spring.output.ansi.enabled=ALWAYS

#Kafka
spring.kafka.bootstrap-servers=47.129.225.147:9092
spring.kafka.consumer.group-id=chill-and-chill
app.kafka.request-topic=moderation_requests
app.kafka.reply-topic=new-post-response-topic

#AWS S3
aws.access.key.id=${AWS_ACCESS_KEY_ID:AKIAXD4SARHXTGKWBFOE}
aws.secret.key.id=${AWS_SECRET_KEY_ID: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}
aws.s3.bucket.name=${AWS_S3_BUCKET_NAME:chillandchill-media-storage}
aws.region=${AWS_REGION:ap-southeast-1}

#JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#JWT
jwt.secret=${JWT_SECRET_KEY:52344E62DC399D1A15AC51A65F1DE}
#Expiration time (minutes)
jwt.access.expiration_time=${JWT_ACCESS_EXPIRATION_TIME:180}
jwt.refresh.expiration_time=${JWT_REFRESH_EXPIRATION_TIME:1440}

cron.deleteExpiredTokenBlacklist=0 0 1 * * *

#Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:ddod32npo}
cloudinary.api_key=${CLOUDINARY_API_KEY:576145563363636}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:PCMzQkOOhdGXoXYjQhmkTvL1qbw}


#Swagger
springdoc.api-docs.enabled=true
springdoc.packagesToScan=com.example.projectbase.controller
springdoc.pathsToMatch=/**

#Infor Mail Send OTP
spring.mail.username=${MAIL_USERNAME:hitchillguy@gmail.com}
spring.mail.password=${MAIL_PASSWORD:knargisougetmdft}

#Info Admin
admin.username=${ADMIN_USERNAME:admin}
admin.password=${ADMIN_PASSWORD:admin}
admin.lastName=${ADMIN_LASTNAME:chill}
admin.firstName=${ADMIN_FIRSTNAME:guy}
admin.email=${ADMIN_EMAIL:admin@example.com}

spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE:400MB}
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE:400MB}

# OAuth2 Client GoogleConfiguration
spring.security.oauth2.client.registration.google.client-id=${OAUTH2_GOOGLE_CLIENT_ID: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}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=${OAUTH2_GOOGLE_SCOPE:openid,profile,email}
spring.security.oauth2.client.registration.google.redirect-uri=${OAUTH2_REDIRECT_URI:https://leminhi.id.vn/login/oauth2/code/{registrationId}}

spring.security.oauth2.client.registration.facebook.client-id=${OAUTH2_FACEBOOK_CLIENT_ID:1267106308102422}
spring.security.oauth2.client.registration.facebook.client-secret=${OAUTH2_FACEBOOK_CLIENT_SECRET:363e9f5094ada7d056cd371d043f22ae}
spring.security.oauth2.client.registration.facebook.scope=${OAUTH2_FACEBOOK_SCOPE:email,public_profile}
spring.security.oauth2.client.registration.facebook.redirect-uri=${OAUTH2_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}
spring.security.oauth2.client.registration.facebook.provider=${OAUTH2_FACEBOOK_PROVIDER:facebook}

# Provider info
spring.security.oauth2.client.provider.facebook.authorization-uri=${OAUTH2_FACEBOOK_AUTHORIZATION_URL:https://www.facebook.com/v23.0/dialog/oauth}
spring.security.oauth2.client.provider.facebook.token-uri=${OAUTH2_FACEBOOK_TOKEN_URI:https://graph.facebook.com/v23.0/oauth/access_token}
spring.security.oauth2.client.provider.facebook.user-info-uri=${OAUTH2_FACEBOOK_USER_INFO_URI:https://graph.facebook.com/me?fields=id,name,email,first_name,last_name,picture}
spring.security.oauth2.client.provider.facebook.user-name-attribute=${OAUTH2_FACEBOOK_USERNAME_ATTRIBUTE:id}

#Redis cloud
spring.redis.host=${REDIS_HOST:redis-19752.crce178.ap-east-1-1.ec2.redns.redis-cloud.com}
spring.redis.port=${REDIS_PORT:19752}
spring.redis.client-name=${REDIS_CLIENT_NAME:ADMIN}
spring.redis.password=${REDIS_PASSWORD:zdDAc014pjnDLCtTNjNQlS89sveBxLzW}
spring.redis.database=${REDIS_DATABASE:0}