#App
server.port=8080

#DATABASE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/chillandchill?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456789

#JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#JWT
jwt.secret=52344E62DC399D1A15AC51A65F1DE
#Expiration time (minutes)
jwt.access.expiration_time=60
jwt.refresh.expiration_time=1440

#Cloudinary
cloudinary.cloud_name=ddod32npo
cloudinary.api_key=576145563363636
cloudinary.api_secret=PCMzQkOOhdGXoXYjQhmkTvL1qbw


#Swagger
springdoc.api-docs.enabled=true
springdoc.packagesToScan=com.example.projectbase.controller
springdoc.pathsToMatch=/**

mail.username=
mail.password=

#Info Admin
admin.username=admin
admin.password=admin
admin.lastName=chill
admin.firstName=guy

spring.servlet.multipart.max-request-size=400MB
spring.servlet.multipart.max-file-size=400MB

# OAuth2 Client GoogleConfiguration
spring.security.oauth2.client.registration.google.client-id=164247824392-ev7t86a8u1ndcn832petev07khqthdrg.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.facebook.client-id=2341492576269466
spring.security.oauth2.client.registration.facebook.client-secret=4229e71b263de8ecbd53d93975cb7905
spring.security.oauth2.client.registration.facebook.scope=email,public_profile,user_birthday
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/facebook
spring.security.oauth2.client.registration.facebook.provider=facebook

# Provider info
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v10.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v10.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,first_name,last_name,picture,gender,birthday
spring.security.oauth2.client.provider.facebook.user-name-attribute=id